### ISSUE TITLE
Crash when clicking on "Use Blueprint" after "Hot Shots" update. 

### ISSUE THREAD

**Issue by dorfman2** [Pt-Djefferson/ONIMods#10]
[Looks like the latest update](https://store.steampowered.com/news/app/457140/view/5922827521631094666?l=english) dubbed "Hot Shots" has broken the mod. There are some new buildings, so I'm not really that surprised. Let me know what I can provide to help troubleshoot.

Attached is my Player.log file

## Steps to Reproduce

1. Open existing game with, Blueprints Fixed mod enabled, Spaced Out DLC enabled.
2. Click on "Use Blueprint."
3. See crash screen.

[Player.log](https://github.com/Pt-Djefferson/ONIMods/files/10240448/Player.log)

**Comment by Pt-Djefferson** [comment]
waiting for PLib update

**Comment by Berkays** [comment]
Are you sure about PLib being the issue? I recompiled this and it did work. Only problem was It was not picking up some buildings which caused by `building.Def.IsBuildable()` returning false at https://github.com/Pt-Djefferson/ONIMods/blob/0df9331a73846ba942d1cbc5610188d26a4ef0f3/Blueprints/BlueprintsStrings.cs#L211

It seems to work fine after deleting that condition.

**Comment by Pt-Djefferson** [comment]
mod updated

**Comment by dorfman2** [comment]
You are amazing! Thanks so much!
